webapp/config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "registrations"}
	resources :groups
	resources :users
	get 'home/index'

	root 'home#index'

end

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<style>
.bodybg {
	background-image: url(<%= asset_path 'bg.jpg' %>);
	background-repeat: no-repeat;
	background-attachment: fixed;
	background-position: center;
	background-size: cover;
}

.tinytext { font-size: .15em; }
.blue-grey-darken-4-alpha { background-color: rgba(38, 50, 56, .8) !important; }
.blue-grey-darken-4-alpha-2 { background-color: rgba(38, 50, 56, .5) !important; }
.blue-grey-darken-3-alpha { background-color: rgba(55, 71, 79, .8) !important; }
.blue-grey-darken-3-alpha-2 { background-color: rgba(55, 71, 79, .5) !important; }
		
.pgptext {
	height:250px !important;
	resize: none !important;
	font-size: .2em; 
	width: 80%;
}

.card-title {
	font-size: 1em !important;
}
		
	
	</style>
	<title>Encryptomail</title>
	<%= stylesheet_link_tag		'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' />
</head>

<body class="bodybg">
	
	<nav class="blue-grey darken-3" role="navigation">
		
		<div class="nav-wrapper container"><a id="logo-container" href="<%= home_index_path %>" class="brand-logo">EncryptoMail</a>
			
			<ul class="right hide-on-med-and-down">
				<% if user_signed_in? %>
					<li>
						<%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "btn red darken-3 white-text") %>
						<%= link_to('My Account', user_session_path, :class => "btn green darken-3 white-text") %>	
					</li>
				<% else %>
					<li>
						<%= link_to('Register', new_user_registration_path, :class => "btn green darken-3 white-text") %>
						<%= link_to('Login', new_user_session_path, :class => "btn green darken-3 white-text") %>
					</li>
				<% end %>
			</ul>

			<ul id="nav-mobile" class="side-nav">
				<% if user_signed_in? %>
					<li>
						<%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "btn red darken-3 white-text") %>
					</li>
					<li>
						<%= link_to('My Account', user_session_path, :class => "btn green darken-3 white-text") %>
					</li>
				<% else %>
					<li>
						<%= link_to('Register', new_user_registration_path, :class => "btn green darken-3 white-text") %>
						<%= link_to('Login', new_user_session_path, :class => "btn green darken-3 white-text") %>
					</li>
				<% end %>
			</ul>
			<a href="#" data-activates="nav-mobile" class="button-collapse">
				<i class="material-icons">menu</i>
			</a>
		</div>
	</nav>
	
	<div class="container white-text">

		<div class="col s12 center-align">
			<!-- I made alerts red, and let notices be green. Since usually alerts bad and notices are not -->
			<p class="notice green-text"><%= notice %></p>
			<p class="alert red-text"><%= alert %></p>
		</div>

		<%= yield %>

	</div>
	<script>
 		$(document).ready(function(){
   			// Activate the side menu 
   			$(".button-collapse").sideNav();
  		});
	</script>
	
</body>
</html>