webapp/config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "registrations"}
	resources :groups
	resources :users
	get 'home/index'

	root 'home#index'

end

webapp/app/models/group.rb
class Group
	include Mongoid::Document

	#name of group when entered
	field :group_name, type: String
	has_and_belongs_to_many :users
	#If we want to let groups set their email
	#field :custom_email, String
	#otherwise, the group email is used

	#automagically generate emails for groups based on their group name and the domain (default = "@encryptomail.net")
	#The problem is 	
	#def email
	#	group_name + Encryptomail::Application.$Domain
	#end
	
	field :email, type: String

	#Encryption keys
	field :pub_key, type: String
	field :pri_key, type: String

	#Default for booleans should be false

	#True if the group cannot change size, false if it is dynamic.
	field :lock_members, type: Boolean

	#True if the group is to be listed openly, false if not.
	field :visible, type: Boolean

	#True if only group members can send to group email, false if open for everyone.
	field :private, type: Boolean

	field :description, type: String
	
	field :leaders, type: Array
	
	index({ group_name: 1 }, { unique: true, name: "group_name_index" })
	index({ email: 1 }, { unique: true, name: "email_index" })	
	
	def leader?(user)
		if leaders.nil? 
			false	
		else
			leaders.include?( user.id.to_s)		
		end
	end
	
	def addUser(email)
		if email.nil?
			false
		else
			if User.where(email: email).exists?
				u = User.find_by(email: email)
			else
				u = nil
				#TBD: Send invite email to email
			end
			self.users << u
		end
	
	end

	
end

webapp/app/controllers/groups_controller.rb
require 'keygenerator'

class GroupsController < EndUserBaseController
	before_action :set_group, only: [:show, :edit, :update, :destroy]

	# GET /groups
	# GET /groups.json
	def index
		@groups = current_user.groups
	end
	
	# GET /groups/1
	# GET /groups/1.json
	def show
		if !@group.users.include? current_user
			redirect_to "/users/"+current_user.id, alert: "You are not allowed to view that page."
		end
	end

	# GET /groups/new
	def new
		@user = current_user
		@group = Group.new
	end

	# GET /groups/1/edit
	def edit
		@user = User.all
	end

	# POST /groups
	# POST /groups.json
	def create
		
		@group = Group.new(group_params)
		
		@group.users << current_user
		@group.leaders = [current_user.id.to_s]
		#The created group email should be "group-name + group-id", this will prevent people making groups of the same name
		# with matching emails. Also this makes it so we don't have to return a "this group already exists" error, which would
		# allow people to infer the name of groups on the system
		#We must save first to get an id generated however
		puts "DEBUG==============="
		gname = @group.group_name.gsub(/\s/, "")
		puts gname
		puts "===================="
		if gname =~ /^[a-zA-Z0-9]+$/
			@group.save
			
			@group.email = gname + "+" + @group.id + $Domain
			puts "DEBUG======2========"
			puts @group.email
			puts "===================="
			# Passphrase for pgp keys is bull-s*** right now, may change later
			KeyGenerator::generatePGPkeyGPGme(@group.group_name, @group.email, "asldkfjlksdjf")

			current_user.save

			
			respond_to do |format|
				if @group.save
					format.html { redirect_to @group, notice: 'Group was successfully created.' }
					format.json { render :show, status: :created, location: @group }
				else
					format.html { render :new }
					format.json { render json: @group.errors, status: :unprocessable_entity }
				end
			end
		else
			respond_to do |format|
				format.html { redirect_to root_url, notice: 'Group was NOT created. Group name must be alpha-numeric characters.'}
			end
		end

	end

	# PATCH/PUT /groups/1
	# PATCH/PUT /groups/1.json
	def update
		respond_to do |format|
			if @group.update(group_params)
				@group.addUser(params[:group_add_user])
				format.html { redirect_to @group, notice: 'Group was successfully updated.' }
				format.json { render :show, status: :ok, location: @group }
			else
				format.html { render :edit }
				format.json { render json: @group.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /groups/1
	# DELETE /groups/1.json
	def destroy
		KeyGenerator::deletekey(@group.email)
		
		@group.destroy
		respond_to do |format|
			format.html { redirect_to root_url, notice: 'Group was successfully destroyed.' }
			format.json { head :no_content }
		end
	end
	

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_group
			@group = Group.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def group_params
			params.require(:group).permit(:group_name, :pub_key, :description)
			
			#gr_name = params.require(:group).group_name
			
		end
	def group_edit_params
			params.require(:group).permit(:group_name, :pub_key, :description)
			params.permit(:group_add_user)
		end
end

webapp/app/helpers/groups_helper.rb
module GroupsHelper
end

webapp/app/views/groups/_form.html.erb
<%= form_for(@group, :html=> {:onsubmit=>'return groupCheck()'}) do |f| %>
	<div class="col s12">
		<% if @group.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
				<ul>
				<% @group.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			</div>
		<% end %>
	</div>

	<div class="col s12">
		<div class="field">
			<input type="text" value="" name="group[email]" id="group_email" class="hide">
			
			<% if @group.new_record? %>

				<div class="input-field">
					<i class="material-icons prefix">assignment_ind</i>
					<%= f.label :group_name, for:"group_group_name" %>
					<%= f.text_field :group_name, class:"validate" %>
				</div>
				
				<div class="input-field">
					<i class="material-icons prefix">mode_edit</i>
					<%= f.label :description, for:"group_description" %>
					<%= f.text_field :description, class:"validate" %>
				</div>
			
			<% else %>
			
				<div class="input-field">
					<i class="material-icons prefix">mode_edit</i>
					<%= f.label :description, for:"group_description" %>
					<%= f.text_field :description, class:"validate", autofocus: true %>
				</div>
			
			<% end %>
			
			<% if !@group.new_record? %>
			
			<div class="input-field">
				<i class="material-icons prefix">recent_actors</i>
				<label for="group_add_user">Additional Users</label>
				<input type="text" value="" name="group_add_user" id="group_add_user" class="validate">
			</div>
			
			<% end %>
			
		</div>
	</div>
	<div class="row actions">
		<div class="col s12">   
			<%= f.submit nil, class: "waves-effect waves-light btn green darken-3", id: "gsb" %>
		</div>	
	</div>
<% end %>

<script>
	function groupCheck() {
		console.log("here");
		var form = document.forms["new_group"];
		if(form){
			form.elements["group_group_name"].value = form.elements["group_group_name"].value.replace(/[<|>|)|(|@|/|*|-|#|]/g, '');
			if(form.elements["group_group_name"].value){
				console.log("TRUE");
				console.log(form.elements["group_group_name"].value);
				return true;
			}
			else {
				console.log("FALSE")
			}
		}
	}
</script>
<script>
	$(document).ready(function() {
		$("#gsb").click(submitButton_OnClick);
	});
	
	function submitButton_OnClick() {
		$("#gsb").val("***CREATING***");
		$("#gsb").attr("disabled", "disabled");
		console.log("Test");
		if ($("form")) {
			$("form").first().submit();
		}
	}
</script>

webapp/app/views/groups/edit.html.erb
<div class="row">
	<div class="col s12 m6 offset-m3 center">
		<h3>Edit <%= @group.group_name %></h3>
	</div>
</div>

<div class="row">
	<div class="col s12 m6 offset-m3 card blue-grey-darken-3-alpha center">
			
		<div class="col s12">
			<%= render 'form' %>
		</div>
			
		<div class="row actions">
			<div class="col s12 m6 offset-m3 center">
				<%= button_to "Delete Group", @group, method: :delete, data: { confirm: "Are you sure?" }, class: "waves-effect waves-light btn red darken-3"%>
			</div>	
		</div>
					
	</div>
</div>

webapp/app/views/groups/index.html.erb
<!--
Honestly we shouldn't list out any of this stuff on an index. Users may look at groups they belong to on their user page.


<h1>Listing Groups</h1>

<table>
	<thead>
		<tr>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% # @groups.each do |group| %>
			<tr>
				<td><%= # group.group_name %></td>
				<td><%= # group.email %></td>
				<td><%= # link_to 'Show', group %></td>
				<td><%= # link_to 'Leave', group %></td>
			</tr>
		<% # end %>
	</tbody>
</table>

<br>-->

webapp/app/views/groups/new.html.erb
<div class="row">
	<div class="col s12 m6 offset-m3 card blue-grey-darken-3-alpha center">
		<h1>New Group</h1>
	
		<div class="col s12">
			<%= render 'form' %>
		</div>
		
		<div class="row">
			<div class="col s12">
				<%= link_to "Back", @user, class: "waves-effect waves-light btn green darken-3" %>
			</div>
		</div>
		
	</div>
</div>

webapp/app/views/groups/show.html.erb
<script>
	<!-- Code from http://codetheory.in/javascript-copy-to-clipboard-without-flash-using-cut-and-copy-commands-with-document-execcommand/ -->
	var copyBtn = document.querySelector('#pubkey_btn');
	copyBtn.addEventListener('click', function () {
		var urlField = document.querySelector('#pub_key');

		// create a Range object
		var range = document.createRange();	
		// set the Node to select the "range"
		range.selectNode(urlField);
		// add the Range to the set of window selections
		window.getSelection().addRange(range);

		// execute 'copy', can't 'cut' in this case
		document.execCommand('copy');
	}, false);
</script>

<div class="row">
	<div class="col s12 card blue-grey-darken-3-alpha">
		<h3 style="text-align: center">Group: <%= @group.group_name %></h3>
	</div>
	
	<div class="col s12 m6 card medium blue-grey-darken-3-alpha">
		<p style="text-align: center">
			Email: 
			<div class="blue-grey-darken-4-alpha-2 amber-text center-align" style="word-wrap: break-word;"><%= @group.email %></div>
		</p>
		<% if @group.leader? current_user %>
			<div class="amber divider"></div>
			<br>
			<div  class="center-align">
				<a href="<%= edit_group_path(@group) %>" class="waves-effect waves-light btn green darken-3" id="edit">
					<i class="material-icons right" value="copy" type="button">mode_edit</i>Edit Group 
				</a>
			</div>
	  	<% end %>
	</div>
	
	<div class="col s12 m6 card medium blue-grey-darken-3-alpha">
		<div class="row">
			<h5 class="left" style="margin: 15px 0px 0px 15px" >Public Key:</h5>
			<a class="waves-effect waves-light right btn green darken-3" id="pubkey_btn" style="margin: 15px 15px 0px 0px" >
				<i class="material-icons right" value="copy" type="button">vpn_key</i>Copy 
			</a>
		</div>
		<div class="center">
        	<textarea rows="16" id="pub_key" name="pub_key" class="validate pgptext tinytext" type="text" readonly>
<%= KeyGenerator::exportpublickeyGPGme(@group.email) %>
			</textarea>
		</div>
	</div>
</div>

<div class="section">
	
	<div class="row blue-grey-darken-3-alpha white-text">
		
		<div class="col s12">
			<h3 style="text-align: center">Users:</h3>
		</div>
				
		<% @group.users.each do |user| %>
		<div class="col s12 m6 l4">
			<div class="card blue-grey-darken-4-alpha-2">
				<div class="card-content center-align white-text">
					<span class="card-title"><span style="word-wrap: break-word"><%= user.email %></span></span>
					<p>PGP Public Key:</p>
					<a class="waves-effect waves-light right btn green darken-3" id="pubkey_btn">
						<i class="material-icons right" value="copy" type="button">vpn_key</i>Copy 
					</a>
					<div class="center">
						<textarea rows="16" id="pub_key<%= user._id %>" name="pub_key" class="pgptext" type="text" readonly>
<%= user.pub_key %>
						</textarea>
					</div>
				</div>
			</div>
		</div>
		<% end %>
		<div class="col s12 center"><h5><br><br><br><br></h5></div>
		
	</div>
	
</div>