webapp/config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => {:registrations => "registrations"}
	resources :groups
	resources :users
	get 'home/index'

	root 'home#index'

end

webapp/app/models/user.rb
class User
	include Mongoid::Document
	# Include default devise modules. Others available are:
	# :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :confirmable, 
				 :recoverable, :rememberable, :trackable, :validatable

	## Database authenticatable
	field :email,							type: String, default: ""
	field :encrypted_password, type: String, default: ""

	## Recoverable
	field :reset_password_token,	 type: String
	field :reset_password_sent_at, type: Time

	## Rememberable
	field :remember_created_at, type: Time

	## Trackable
	field :sign_in_count,			type: Integer, default: 0
	field :current_sign_in_at, type: Time
	field :last_sign_in_at,		type: Time
	field :current_sign_in_ip, type: String
	field :last_sign_in_ip,		type: String

	## Confirmable
	field :confirmation_token,	 type: String
	field :confirmed_at,				 type: Time
	field :confirmation_sent_at, type: Time
	# field :unconfirmed_email,		type: String # Only if using reconfirmable

	## Lockable
	# field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
	# field :unlock_token,		type: String # Only if unlock strategy is :email or :both
	# field :locked_at,			 type: Time
	
	has_and_belongs_to_many :groups
	
	field :user_name, type: String
	
	field :pub_key, type: String
	
	field :register_date, type: DateTime, :default => DateTime.now
	
	validates_uniqueness_of :email
	#validates_uniqueness_of :pub_key
	
	
end

webapp/app/controllers/users_controller.rb
class UsersController < EndUserBaseController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	# GET /users
	# GET /users.json
	#def index
	#TBD: If we have this route - it will redirect to the user's home page
		#@users = User.all
	#end

	
	
	# GET /users/1
	# GET /users/1.json
	def show
		if @user.id != current_user.id
			redirect_to "/users/"+current_user.id, alert: "You are not allowed to view that page."
		end
	end

	# GET /users/new
	def new
		@user = User.new
	end

	# GET /users/1/edit
	def edit
	end

	# POST /users
	# POST /users.json
	def create
		@user = User.new(user_params)
		puts "CREATE USER"
		respond_to do |format|
			if @user.save
				format.html { redirect_to @user, notice: 'User was successfully created.' }
				format.json { render :show, status: :created, location: @user }
			else
				format.html { render :new }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /users/1
	# PATCH/PUT /users/1.json
	def update
		puts "CREATE USER2"
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to @user, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
		@user.destroy
		respond_to do |format|
			format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_user
			@user = User.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def user_params
			params.require(:user).permit(:pass_hash, :password1, :password2, :email, :pub_key)
		end
end

webapp/app/helpers/users_helper.rb
module UsersHelper
end

webapp/app/views/users/_form.html.erb
<%= form_for(@user, as: user, url: user_path(user)) do |f| %>
	<div class="col s12">
		<% if @user.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

				<ul>
				<% @user.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			</div>
		<% end %>
	</div>
	<div class="col s12 m6 offset-m3">
		<div class="field">
			<%= f.label :email %>
			<%= f.text_field :email %>
		</div>
	</div>
	<div class="col s12 m6 offset-m3">
		<div class="field">
			<%= f.label :pub_key %>
			<%= f.text_field :pub_key %>
		</div>
	</div>
	<div class="col s12 m6 offset-m3">
		<div class="actions">
			<%= f.submit nil, :class => "waves-effect waves-light btn green darken-3" %>
		</div>
	</div>
<% end %>

webapp/app/views/users/edit.html.erb
<div class="row">
	<div class="col s12 m6 offset-m3 card blue-grey-darken-3-alpha center">
		<div class="row">

			<div class="col s12">
				<h1>Editing <%= @user.user_name %> </h1>
			</div>
			
			<div class="col s12">
				<%= render 'form' %>
			</div>
			
			<div class="col s12">
				<%= link_to 'Show Profile', @user, :class => "waves-effect waves-light btn green darken-3" %>
			</div>
		</div>
	</div>
</div>

webapp/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

webapp/app/views/users/show.html.erb
<!-- This script allows you to press a button to copy the PGP key -->
<script>
	<!-- Code from http://codetheory.in/javascript-copy-to-clipboard-without-flash-using-cut-and-copy-commands-with-document-execcommand/ -->
	var copyBtn = document.querySelector('#pubkey_btn');
	copyBtn.addEventListener('click', function () {
		var urlField = document.querySelector('#pub_key');
		// create a Range object
		var range = document.createRange();	
		// set the Node to select the "range"
		range.selectNode(urlField);
		// add the Range to the set of window selections
		window.getSelection().addRange(range);
		// execute 'copy', can't 'cut' in this case
		document.execCommand('copy');
	}, false);
</script>

<div class="row">
	<div class="col s12 card blue-grey-darken-3-alpha">
		<h3 style="text-align: center">User: <%= @user.email[/[^@]+/] %></h3>
	</div>
	
	<div class="col s12 m6 card medium blue-grey-darken-3-alpha">
		<p class="center-align">
			Email: 
			<div class="blue-grey-darken-4-alpha-2 amber-text center-align"><%= @user.email %></div>
		</p>
	
		<p class="center-align">Joined: <%= @user.register_date.strftime('%x') %> </p>
		<div class="amber divider"></div>
		<br>
		<div  class="center-align">
			<a href="<%= edit_user_registration_path(@user) %>" class="waves-effect waves-light btn green darken-3"	id="edit">
				<i class="material-icons right" value="copy" type="button">mode_edit</i>Edit Profile 
			</a>
		</div>
	</div>
	<div class="col s12 m6 card medium blue-grey-darken-3-alpha" >
		<div class="row">	
			<div class="col s12 center">
				<h5 class="left" style="margin: 15px 0px 0px 0px" >Public Key:</h5>
				<a class="waves-effect waves-light right btn green darken-3" id="pubkey_btn" style="margin: 10px 0px 0px 0px" >
					<i class="material-icons right" value="copy" type="button">vpn_key</i>Copy 
				</a>
			</div>
		</div>
		<div class="center">
			<textarea rows="16" id="pub_key" name="pub_key" class="validate pgptext tinytext" type="text" readonly>
<%= @user.pub_key %>
			</textarea>
		</div>	
	</div>
</div>

<div class= "section">
	
	<div class="row blue-grey-darken-3-alpha white-text">
		<div class="col s12">
			<h3 style="text-align: center">Groups:</h3>
			<div class="center-align">
				<a class="waves-effect waves-light btn green darken-3" href="<%= new_group_path %>">
					<i class="material-icons right">group_add</i>Create
				</a>
			</div>
		</div>
		
		<% @user.groups.each do |g| %>
		<div class="col s12 m6 l4">
			<div class="card blue-grey-darken-4-alpha-2">
				<div class="card-content center-align white-text">
					<span class="card-title" style="word-wrap: break-word"><%= g.group_name %></span>
					<p><%= g.description %></p>
				</div>
				<div class="card-action center-align">
					<a href="<%= group_path(g) %>" class="waves-effect waves-lilght btn green darken-3">
						Group Page <i class="material-icons right">keyboard_arrow_right</i>
					</a>
				</div>
			</div>
		</div>
		<% end %>
		<div class="col s12 center"><h5><br><br><br><br></h5></div>
	</div>
	
</div>